on: [push]

jobs:
  build-push:
    runs-on: ubuntu-latest
    name: Compile Typescript
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: yarn
      - name: Compile Typescript
        uses: FuLagann/tsc-build-push@v1
        with:
          user-name: "pgsd"
          user-email: "pgsd@zbamail.ml"
          message: "Compiled TS into JS"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
